name: Test build for brickOS
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        run: sudo apt-get install -y binutils-h8300-hms gcc-h8300-hms brickos
      - name: Compile brickOS examples
        run: make && pwd
      - name: Upload firmware
        uses: actions/upload-artifact@v1.0.0
        with:
          name: brickOS firmware
          path: '/usr/lib/brickos/brickOS.srec'
      - name: Upload user programs
        uses: actions/upload-artifact@v1.0.0
        with:
          name: user programs
          path: helloworld.lx
